"""Simple control-plane orchestration model for MVP demo flows."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from .contract import HandoffPayload


class ActionName(StrEnum):
    """Control-plane actions visible in the MVP UI."""

    CREATE_ENVIRONMENT = "create_environment"
    APPLY_BASELINE = "apply_baseline"
    RUN_COMPLIANCE_SCAN = "run_compliance_scan"
    INJECT_SSH_DRIFT = "inject_ssh_drift"
    INJECT_SERVICE_DRIFT = "inject_service_drift"
    RUN_REMEDIATION = "run_remediation"


class ActionStatus(StrEnum):
    """Result status for an action invocation."""

    SUCCEEDED = "succeeded"
    FAILED = "failed"


@dataclass(frozen=True, slots=True)
class EvidenceRecord:
    """An immutable, machine-readable record for action outcomes."""

    action: ActionName
    status: ActionStatus
    detail: str


class DemoOrchestrator:
    """Minimal in-memory orchestrator used by docs/tests and local demos."""

    def __init__(self) -> None:
        self._evidence: list[EvidenceRecord] = []

    @property
    def evidence(self) -> list[EvidenceRecord]:
        """Return evidence log entries generated by workflow actions."""

        return list(self._evidence)

    def create_environment(self, payload: HandoffPayload) -> EvidenceRecord:
        record = EvidenceRecord(
            action=ActionName.CREATE_ENVIRONMENT,
            status=ActionStatus.SUCCEEDED,
            detail=(
                "Terraform run "
                f"{payload.terraform_run_id} provisioned {payload.target_platform.value}."
            ),
        )
        self._evidence.append(record)
        return record

    def apply_baseline(self) -> EvidenceRecord:
        record = EvidenceRecord(
            action=ActionName.APPLY_BASELINE,
            status=ActionStatus.SUCCEEDED,
            detail="Baseline hardening role set applied.",
        )
        self._evidence.append(record)
        return record

    def run_compliance_scan(self, drift_present: bool) -> EvidenceRecord:
        if drift_present:
            record = EvidenceRecord(
                action=ActionName.RUN_COMPLIANCE_SCAN,
                status=ActionStatus.FAILED,
                detail="Compliance scan detected SSH root-login drift.",
            )
        else:
            record = EvidenceRecord(
                action=ActionName.RUN_COMPLIANCE_SCAN,
                status=ActionStatus.SUCCEEDED,
                detail="Compliance scan passed for current baseline.",
            )

        self._evidence.append(record)
        return record

    def inject_ssh_drift(self) -> EvidenceRecord:
        record = EvidenceRecord(
            action=ActionName.INJECT_SSH_DRIFT,
            status=ActionStatus.SUCCEEDED,
            detail="SSH drift injected: PermitRootLogin yes.",
        )
        self._evidence.append(record)
        return record

    def run_remediation(self) -> EvidenceRecord:
        record = EvidenceRecord(
            action=ActionName.RUN_REMEDIATION,
            status=ActionStatus.SUCCEEDED,
            detail="Remediation restored PermitRootLogin no.",
        )
        self._evidence.append(record)
        return record
